### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by PEPNETKing** [mypepewallet/mypepewallet#2]
When I used yarn to install the required environment, one package showed 404
![image_2024-12-13_01-46-42](https://github.com/user-attachments/assets/fd65f55c-e97e-4ab9-a500-45f499eb1932)

**Comment by mypepewallet** [comment]
dependencies fixed

**Comment by mypepewallet** [comment]
https://github.com/mypepewallet/mypepewallet/commit/03b6f7cb5cb65de1219a18e0832bdd2d46d8e68f
